// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'doc_field.dart';

// **************************************************************************
// CopyWithGenerator
// **************************************************************************

/// This Extension on [DocField] is to generate the code for a copyWith(...) function.
extension $DocFieldCopyWithExtension on DocField {
  DocField copyWith({
    String? name,
    DateTime? creation,
    DateTime? modified,
    String? modifiedBy,
    String? owner,
    int? idx,
    String? module,
    String? sortField,
    String? sortOrder,
    int? maxAttachments,
    int? isSubmittable,
    int? showTitleFieldInLink,
    int? translatedDocType,
    int? allowAutoRepeat,
    DocTypeType? docType,
    int? docStatus,
    String? description,
    String? parent,
    String? parentField,
    String? parentType,
    String? fieldName,
    String? label,
    String? options,
    String? fieldType,
    int? hidden,
    int? setOnlyOnce,
    int? required,
    String? requiredDependsOn,
    int? bold,
    int? collapsible,
    int? unique,
    int? readOnly,
    String? readOnlyDependsOn,
    String? visibilityDependsOn,
    int? inListView,
    int? length,
    int? translatable,
    int? hideDays,
    int? hideSeconds,
    int? nonNegative,
    int? sortOptions,
    Object? initial,
    String? precision,
    Object? childTable,
    String? renderRules,
    List<DocField>? children,
  }) {
    return DocField(
      name: name ?? this.name,
      creation: creation ?? this.creation,
      modified: modified ?? this.modified,
      modifiedBy: modifiedBy ?? this.modifiedBy,
      owner: owner ?? this.owner,
      idx: idx ?? this.idx,
      module: module ?? this.module,
      sortField: sortField ?? this.sortField,
      sortOrder: sortOrder ?? this.sortOrder,
      maxAttachments: maxAttachments ?? this.maxAttachments,
      isSubmittable: isSubmittable ?? this.isSubmittable,
      showTitleFieldInLink: showTitleFieldInLink ?? this.showTitleFieldInLink,
      translatedDocType: translatedDocType ?? this.translatedDocType,
      allowAutoRepeat: allowAutoRepeat ?? this.allowAutoRepeat,
      docType: docType ?? this.docType,
      docStatus: docStatus ?? this.docStatus,
      description: description ?? this.description,
      parent: parent ?? this.parent,
      parentField: parentField ?? this.parentField,
      parentType: parentType ?? this.parentType,
      fieldName: fieldName ?? this.fieldName,
      label: label ?? this.label,
      options: options ?? this.options,
      fieldType: fieldType ?? this.fieldType,
      hidden: hidden ?? this.hidden,
      setOnlyOnce: setOnlyOnce ?? this.setOnlyOnce,
      required: required ?? this.required,
      requiredDependsOn: requiredDependsOn ?? this.requiredDependsOn,
      bold: bold ?? this.bold,
      collapsible: collapsible ?? this.collapsible,
      unique: unique ?? this.unique,
      readOnly: readOnly ?? this.readOnly,
      readOnlyDependsOn: readOnlyDependsOn ?? this.readOnlyDependsOn,
      visibilityDependsOn: visibilityDependsOn ?? this.visibilityDependsOn,
      inListView: inListView ?? this.inListView,
      length: length ?? this.length,
      translatable: translatable ?? this.translatable,
      hideDays: hideDays ?? this.hideDays,
      hideSeconds: hideSeconds ?? this.hideSeconds,
      nonNegative: nonNegative ?? this.nonNegative,
      sortOptions: sortOptions ?? this.sortOptions,
      initial: initial ?? this.initial,
      precision: precision ?? this.precision,
      childTable: childTable ?? this.childTable,
      renderRules: renderRules ?? this.renderRules,
      children:
          ((children?.isNotEmpty ?? false) ? children : null) ?? this.children,
    );
  }
}

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DocField _$DocFieldFromJson(Map<String, dynamic> json) => DocField(
  name: json['name'] as String?,
  creation: json['creation'] == null
      ? null
      : DateTime.parse(json['creation'] as String),
  modified: json['modified'] == null
      ? null
      : DateTime.parse(json['modified'] as String),
  modifiedBy: json['modified_by'] as String?,
  owner: json['owner'] as String?,
  idx: (json['idx'] as num?)?.toInt(),
  module: json['module'] as String?,
  sortField: json['sort_field'] as String?,
  sortOrder: json['sort_order'] as String?,
  maxAttachments: (json['max_attachments'] as num?)?.toInt(),
  isSubmittable: (json['is_submittable'] as num?)?.toInt(),
  showTitleFieldInLink: (json['show_title_field_in_link'] as num?)?.toInt(),
  translatedDocType: (json['translated_doctype'] as num?)?.toInt(),
  allowAutoRepeat: (json['allow_auto_repeat'] as num?)?.toInt(),
  docType: $enumDecodeNullable(
    _$DocTypeTypeEnumMap,
    json['doctype'],
    unknownValue: JsonKey.nullForUndefinedEnumValue,
  ),
  docStatus: (json['docstatus'] as num?)?.toInt(),
  description: json['description'] as String?,
  parent: json['parent'] as String?,
  parentField: json['parentfield'] as String?,
  parentType: json['parenttype'] as String?,
  fieldName: json['fieldname'] as String?,
  label: json['label'] as String?,
  options: json['options'] as String?,
  fieldType: json['fieldtype'] as String?,
  hidden: (json['hidden'] as num?)?.toInt(),
  setOnlyOnce: (json['set_only_once'] as num?)?.toInt(),
  required: (json['reqd'] as num?)?.toInt(),
  requiredDependsOn: json['mandatory_depends_on'] as String?,
  bold: (json['bold'] as num?)?.toInt(),
  collapsible: (json['collapsible'] as num?)?.toInt(),
  unique: (json['unique'] as num?)?.toInt(),
  readOnly: (json['read_only'] as num?)?.toInt(),
  readOnlyDependsOn: json['read_only_depends_on'] as String?,
  visibilityDependsOn: json['depends_on'] as String?,
  inListView: (json['in_list_view'] as num?)?.toInt(),
  length: (json['length'] as num?)?.toInt(),
  translatable: (json['translatable'] as num?)?.toInt(),
  hideDays: (json['hide_days'] as num?)?.toInt(),
  hideSeconds: (json['hide_seconds'] as num?)?.toInt(),
  nonNegative: (json['non_negative'] as num?)?.toInt(),
  sortOptions: (json['sort_options'] as num?)?.toInt(),
  initial: json['default'],
  precision: json['precision'] as String?,
  childTable: json['child_table'],
  renderRules: json['render_rules'] as String?,
);

Map<String, dynamic> _$DocFieldToJson(DocField instance) => <String, dynamic>{
  'name': ?instance.name,
  'creation': ?instance.creation?.toIso8601String(),
  'modified': ?instance.modified?.toIso8601String(),
  'modified_by': ?instance.modifiedBy,
  'owner': ?instance.owner,
  'idx': ?instance.idx,
  'module': ?instance.module,
  'sort_field': ?instance.sortField,
  'sort_order': ?instance.sortOrder,
  'max_attachments': ?instance.maxAttachments,
  'is_submittable': ?instance.isSubmittable,
  'show_title_field_in_link': ?instance.showTitleFieldInLink,
  'translated_doctype': ?instance.translatedDocType,
  'allow_auto_repeat': ?instance.allowAutoRepeat,
  'doctype': ?_$DocTypeTypeEnumMap[instance.docType],
  'docstatus': ?instance.docStatus,
  'description': ?instance.description,
  'parent': ?instance.parent,
  'parentfield': ?instance.parentField,
  'parenttype': ?instance.parentType,
  'fieldname': ?instance.fieldName,
  'label': ?instance.label,
  'options': ?instance.options,
  'fieldtype': ?instance.fieldType,
  'hidden': ?instance.hidden,
  'set_only_once': ?instance.setOnlyOnce,
  'reqd': ?instance.required,
  'mandatory_depends_on': ?instance.requiredDependsOn,
  'bold': ?instance.bold,
  'collapsible': ?instance.collapsible,
  'unique': ?instance.unique,
  'read_only': ?instance.readOnly,
  'read_only_depends_on': ?instance.readOnlyDependsOn,
  'depends_on': ?instance.visibilityDependsOn,
  'in_list_view': ?instance.inListView,
  'length': ?instance.length,
  'translatable': ?instance.translatable,
  'hide_days': ?instance.hideDays,
  'hide_seconds': ?instance.hideSeconds,
  'non_negative': ?instance.nonNegative,
  'sort_options': ?instance.sortOptions,
  'default': ?instance.initial,
  'precision': ?instance.precision,
  'child_table': ?instance.childTable,
  'render_rules': ?instance.renderRules,
};

const _$DocTypeTypeEnumMap = {
  DocTypeType.docType: 'DocType',
  DocTypeType.docField: 'DocField',
};
