class DocFormSamples {
  static const fieldTest = {
    "doctype": "DocType",
    "name": "Item",
    "creation": "2013-05-03 10:45:46",
    "modified": "2025-08-08 14:58:48.674193",
    "modified_by": "Administrator",
    "owner": "Administrator",
    "docstatus": 0,
    "idx": 2,
    "search_fields": "item_name,description,item_group,customer_code",
    "issingle": 0,
    "is_virtual": 0,
    "is_tree": 0,
    "istable": 0,
    "editable_grid": 1,
    "track_changes": 1,
    "module": "Stock",
    "autoname": "field:item_code",
    "naming_rule": "By fieldname",
    "title_field": "item_name",
    "image_field": "image",
    "sort_field": "modified",
    "sort_order": "DESC",
    "description":
        "A Product or a Service that is bought, sold or kept in stock.",
    "read_only": 0,
    "in_create": 0,
    "allow_copy": 0,
    "allow_rename": 1,
    "allow_import": 1,
    "hide_toolbar": 0,
    "track_seen": 0,
    "max_attachments": 0,
    "document_type": "Setup",
    "icon": "fa fa-tag",
    "engine": "InnoDB",
    "is_submittable": 0,
    "show_name_in_global_search": 1,
    "custom": 0,
    "beta": 0,
    "has_web_view": 0,
    "allow_guest_to_view": 0,
    "email_append_to": 0,
    "show_title_field_in_link": 0,
    "migration_hash": "393e5e1e0a0ac34e621b4483515379f6",
    "translated_doctype": 0,
    "is_calendar_and_gantt": 0,
    "quick_entry": 1,
    "grid_page_length": 0,
    "rows_threshold_for_grid_search": 0,
    "track_views": 0,
    "queue_in_background": 0,
    "allow_events_in_timeline": 0,
    "allow_auto_repeat": 0,
    "make_attachments_public": 1,
    "force_re_route_to_default_view": 0,
    "show_preview_popup": 1,
    "protect_attached_files": 0,
    "index_web_pages_for_search": 0,
    "row_format": "Dynamic",
    "fields": [
      //  ---------------------------
      //     this is the section
      {
        "doctype": "DocField",
        "name": "271vtktd7a",
        "creation": "2013-05-03 10:45:46",
        "modified": "2025-11-25 13:52:33.795717",
        "modified_by": "Administrator",
        "owner": "Administrator",
        "docstatus": 0,
        "parent": "Item",
        "parentfield": "fields",
        "parenttype": "DocType",
        "idx": 27,
        "fieldname": "unit_of_measure_conversion",
        "label": "Units of Measure",
        "fieldtype": "Section Break",
        "search_index": 0,
        "show_dashboard": 0,
        "hidden": 0,
        "set_only_once": 0,
        "allow_in_quick_entry": 0,
        "print_hide": 0,
        "report_hide": 0,
        "reqd": 0,
        "bold": 0,
        "in_global_search": 0,
        "collapsible": 1,
        "unique": 0,
        "no_copy": 0,
        "allow_on_submit": 0,
        "show_preview_popup": 0,
        "permlevel": 0,
        "ignore_user_permissions": 0,
        "columns": 0,
        "in_list_view": 0,
        "fetch_if_empty": 0,
        "in_filter": 0,
        "remember_last_selected_value": 0,
        "ignore_xss_filter": 0,
        "print_hide_if_no_value": 0,
        "allow_bulk_edit": 0,
        "in_standard_filter": 0,
        "in_preview": 0,
        "read_only": 0,
        "length": 0,
        "translatable": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "non_negative": 0,
        "is_virtual": 0,
        "sort_options": 0,
        "show_on_timeline": 0,
        "make_attachment_public": 0,
        "fields": [],
        "permissions": [],
        "actions": [],
        "links": [],
        "states": [],
        // "child_table"
        "search_fields": null,
        "is_custom_field": null,
        "linked_document_type": null,
      },

      //  ---------------------------
      {
        "doctype": "DocField",
        "name": "271tcvrppo",
        "creation": "2013-05-03 10:45:46",
        "modified": "2025-11-25 13:52:33.795717",
        "modified_by": "Administrator",
        "owner": "Administrator",
        "docstatus": 0,
        "parent": "Item",
        "parentfield": "fields",
        "parenttype": "DocType",
        "idx": 28,
        "fieldname": "uoms",
        "label": "UOMs",
        "oldfieldname": "uom_conversion_details",
        "fieldtype": "Table",
        "oldfieldtype": "Table",
        "options": "UOM Conversion Detail",
        "search_index": 0,
        "show_dashboard": 0,
        "hidden": 0,
        "set_only_once": 0,
        "allow_in_quick_entry": 0,
        "print_hide": 0,
        "report_hide": 0,
        "reqd": 0,
        "bold": 0,
        "in_global_search": 0,
        "collapsible": 0,
        "unique": 0,
        "no_copy": 0,
        "allow_on_submit": 0,
        "show_preview_popup": 0,
        "permlevel": 0,
        "ignore_user_permissions": 0,
        "columns": 0,
        "description": "Will also apply for variants",
        "in_list_view": 0,
        "fetch_if_empty": 0,
        "in_filter": 0,
        "remember_last_selected_value": 0,
        "ignore_xss_filter": 0,
        "print_hide_if_no_value": 0,
        "allow_bulk_edit": 0,
        "in_standard_filter": 0,
        "in_preview": 0,
        "read_only": 0,
        "length": 0,
        "translatable": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "non_negative": 0,
        "is_virtual": 0,
        "sort_options": 0,
        "show_on_timeline": 0,
        "make_attachment_public": 0,
        "fields": [],
        "permissions": [],
        "actions": [],
        "links": [],
        "states": [],
        "child_table": {
          "name": "UOM Conversion Detail",
          "creation": "2013-02-22 01:28:04",
          "modified": "2016-07-11 03:28:09.626948",
          "modified_by": "Administrator",
          "owner": "Administrator",
          "docstatus": 0,
          "idx": 1,
          "issingle": 0,
          "is_virtual": 0,
          "is_tree": 0,
          "istable": 1,
          "editable_grid": 1,
          "track_changes": 0,
          "module": "Stock",
          "autoname": "hash",
          "sort_field": "modified",
          "sort_order": "DESC",
          "read_only": 0,
          "in_create": 0,
          "allow_copy": 0,
          "allow_rename": 0,
          "allow_import": 0,
          "hide_toolbar": 0,
          "track_seen": 0,
          "max_attachments": 0,
          "engine": "InnoDB",
          "is_submittable": 0,
          "show_name_in_global_search": 0,
          "custom": 0,
          "beta": 0,
          "has_web_view": 0,
          "allow_guest_to_view": 0,
          "email_append_to": 0,
          "show_title_field_in_link": 0,
          "migration_hash": "2c06a2d630824668207d605dd661c5a0",
          "translated_doctype": 0,
          "is_calendar_and_gantt": 0,
          "quick_entry": 0,
          "grid_page_length": 0,
          "rows_threshold_for_grid_search": 0,
          "track_views": 0,
          "queue_in_background": 0,
          "allow_events_in_timeline": 0,
          "allow_auto_repeat": 0,
          "make_attachments_public": 0,
          "force_re_route_to_default_view": 0,
          "show_preview_popup": 0,
          "protect_attached_files": 0,
          "index_web_pages_for_search": 0,
          "row_format": "Dynamic",
          "doctype": "DocType",
          "actions": [],
          "fields": [
            {
              "name": "278p419e1f",
              "creation": "2013-02-22 01:28:04",
              "modified": "2025-11-25 13:52:34.436314",
              "modified_by": "Administrator",
              "owner": "Administrator",
              "docstatus": 0,
              "parent": "UOM Conversion Detail",
              "parentfield": "fields",
              "parenttype": "DocType",
              "idx": 1,
              "fieldname": "uom",
              "label": "UOM",
              "oldfieldname": "uom",
              "fieldtype": "Link",
              "oldfieldtype": "Link",
              "options": "UOM",
              "search_index": 0,
              "show_dashboard": 0,
              "hidden": 0,
              "set_only_once": 0,
              "allow_in_quick_entry": 0,
              "print_hide": 0,
              "report_hide": 0,
              "reqd": 0,
              "bold": 0,
              "in_global_search": 0,
              "collapsible": 0,
              "unique": 0,
              "no_copy": 0,
              "allow_on_submit": 0,
              "show_preview_popup": 0,
              "permlevel": 0,
              "ignore_user_permissions": 0,
              "columns": 0,
              "in_list_view": 1,
              "fetch_if_empty": 0,
              "in_filter": 0,
              "remember_last_selected_value": 0,
              "ignore_xss_filter": 0,
              "print_hide_if_no_value": 0,
              "allow_bulk_edit": 0,
              "in_standard_filter": 0,
              "in_preview": 0,
              "read_only": 0,
              "length": 0,
              "translatable": 0,
              "hide_border": 0,
              "hide_days": 0,
              "hide_seconds": 0,
              "non_negative": 0,
              "is_virtual": 0,
              "sort_options": 0,
              "show_on_timeline": 0,
              "make_attachment_public": 0,
              "doctype": "DocField",
            },
            {
              "name": "278lqq55im",
              "creation": "2013-02-22 01:28:04",
              "modified": "2025-11-25 13:52:34.436314",
              "modified_by": "Administrator",
              "owner": "Administrator",
              "docstatus": 0,
              "parent": "UOM Conversion Detail",
              "parentfield": "fields",
              "parenttype": "DocType",
              "idx": 2,
              "fieldname": "conversion_factor",
              "label": "Conversion Factor",
              "oldfieldname": "conversion_factor",
              "fieldtype": "Float",
              "oldfieldtype": "Float",
              "search_index": 0,
              "show_dashboard": 0,
              "hidden": 0,
              "set_only_once": 0,
              "allow_in_quick_entry": 0,
              "print_hide": 0,
              "report_hide": 0,
              "reqd": 0,
              "bold": 0,
              "in_global_search": 0,
              "collapsible": 0,
              "unique": 0,
              "no_copy": 0,
              "allow_on_submit": 0,
              "show_preview_popup": 0,
              "permlevel": 0,
              "ignore_user_permissions": 0,
              "columns": 0,
              "in_list_view": 1,
              "fetch_if_empty": 0,
              "in_filter": 0,
              "remember_last_selected_value": 0,
              "ignore_xss_filter": 0,
              "print_hide_if_no_value": 0,
              "allow_bulk_edit": 0,
              "in_standard_filter": 0,
              "in_preview": 0,
              "read_only": 0,
              "length": 0,
              "translatable": 0,
              "hide_border": 0,
              "hide_days": 0,
              "hide_seconds": 0,
              "non_negative": 0,
              "is_virtual": 0,
              "sort_options": 0,
              "show_on_timeline": 0,
              "make_attachment_public": 0,
              "doctype": "DocField",
            },
          ],
          "permissions": [],
          "links": [],
          "states": [],
        },
        "default": [
          {
            "name": "gbea26ot8b",
            "owner": "khaled@im2m.ws",
            "creation": "2025-11-25 11:46:41.467015",
            "modified": "2025-11-25 11:46:41.467015",
            "modified_by": "khaled@im2m.ws",
            "docstatus": 0,
            "idx": 1,
            "uom": "Nos",
            "conversion_factor": 1,
            "parent": "SKU004",
            "parentfield": "uoms",
            "parenttype": "Item",
            "doctype": "UOM Conversion Detail",
          },
        ],
      },
      // {
      //   "doctype": "DocField",
      //   "name": "272ts8r138",
      //   "creation": "2013-05-03 10:45:46",
      //   "modified": "2025-11-25 13:52:33.795717",
      //   "modified_by": "Administrator",
      //   "owner": "Administrator",
      //   "docstatus": 0,
      //   "parent": "Item",
      //   "parentfield": "fields",
      //   "parenttype": "DocType",
      //   "idx": 95,
      //   "fieldname": "taxes",
      //   "label": "Taxes",
      //   "oldfieldname": "item_tax",
      //   "fieldtype": "Table",
      //   "oldfieldtype": "Table",
      //   "options": "Item Tax",
      //   "search_index": 0,
      //   "show_dashboard": 0,
      //   "hidden": 0,
      //   "set_only_once": 0,
      //   "allow_in_quick_entry": 0,
      //   "print_hide": 0,
      //   "report_hide": 0,
      //   "reqd": 0,
      //   "bold": 0,
      //   "in_global_search": 0,
      //   "collapsible": 0,
      //   "unique": 0,
      //   "no_copy": 0,
      //   "allow_on_submit": 0,
      //   "show_preview_popup": 0,
      //   "permlevel": 0,
      //   "ignore_user_permissions": 0,
      //   "columns": 0,
      //   "description": "Will also apply for variants",
      //   "in_list_view": 0,
      //   "fetch_if_empty": 0,
      //   "in_filter": 0,
      //   "remember_last_selected_value": 0,
      //   "ignore_xss_filter": 0,
      //   "print_hide_if_no_value": 0,
      //   "allow_bulk_edit": 0,
      //   "in_standard_filter": 0,
      //   "in_preview": 0,
      //   "read_only": 0,
      //   "length": 0,
      //   "translatable": 0,
      //   "hide_border": 0,
      //   "hide_days": 0,
      //   "hide_seconds": 0,
      //   "non_negative": 0,
      //   "is_virtual": 0,
      //   "sort_options": 0,
      //   "show_on_timeline": 0,
      //   "make_attachment_public": 0,
      //   "fields": [],
      //   "permissions": [],
      //   "actions": [],
      //   "links": [],
      //   "states": [],
      //   "default":[],

      // },

      //  ---------------------------
    ],
    "_table_fields": [
      {
        "doctype": "DocField",
        "name": "271tcvrppo",
        "creation": "2013-05-03 10:45:46",
        "modified": "2025-11-25 13:52:33.795717",
        "modified_by": "Administrator",
        "owner": "Administrator",
        "docstatus": 0,
        "parent": "Item",
        "parentfield": "fields",
        "parenttype": "DocType",
        "idx": 28,
        "fieldname": "uoms",
        "label": "UOMs",
        "oldfieldname": "uom_conversion_details",
        "fieldtype": "Table",
        "oldfieldtype": "Table",
        "options": "UOM Conversion Detail",
        "search_index": 0,
        "show_dashboard": 0,
        "hidden": 0,
        "set_only_once": 0,
        "allow_in_quick_entry": 0,
        "print_hide": 0,
        "report_hide": 0,
        "reqd": 0,
        "bold": 0,
        "in_global_search": 0,
        "collapsible": 0,
        "unique": 0,
        "no_copy": 0,
        "allow_on_submit": 0,
        "show_preview_popup": 0,
        "permlevel": 0,
        "ignore_user_permissions": 0,
        "columns": 0,
        "description": "Will also apply for variants",
        "in_list_view": 0,
        "fetch_if_empty": 0,
        "in_filter": 0,
        "remember_last_selected_value": 0,
        "ignore_xss_filter": 0,
        "print_hide_if_no_value": 0,
        "allow_bulk_edit": 0,
        "in_standard_filter": 0,
        "in_preview": 0,
        "read_only": 0,
        "length": 0,
        "translatable": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "non_negative": 0,
        "is_virtual": 0,
        "sort_options": 0,
        "show_on_timeline": 0,
        "make_attachment_public": 0,
        "fields": [],
        "permissions": [],
        "actions": [],
        "links": [],
        "states": [],
      },
      {
        "doctype": "DocField",
        "name": "272ts8r138",
        "creation": "2013-05-03 10:45:46",
        "modified": "2025-11-25 13:52:33.795717",
        "modified_by": "Administrator",
        "owner": "Administrator",
        "docstatus": 0,
        "parent": "Item",
        "parentfield": "fields",
        "parenttype": "DocType",
        "idx": 95,
        "fieldname": "taxes",
        "label": "Taxes",
        "oldfieldname": "item_tax",
        "fieldtype": "Table",
        "oldfieldtype": "Table",
        "options": "Item Tax",
        "search_index": 0,
        "show_dashboard": 0,
        "hidden": 0,
        "set_only_once": 0,
        "allow_in_quick_entry": 0,
        "print_hide": 0,
        "report_hide": 0,
        "reqd": 0,
        "bold": 0,
        "in_global_search": 0,
        "collapsible": 0,
        "unique": 0,
        "no_copy": 0,
        "allow_on_submit": 0,
        "show_preview_popup": 0,
        "permlevel": 0,
        "ignore_user_permissions": 0,
        "columns": 0,
        "description": "Will also apply for variants",
        "in_list_view": 0,
        "fetch_if_empty": 0,
        "in_filter": 0,
        "remember_last_selected_value": 0,
        "ignore_xss_filter": 0,
        "print_hide_if_no_value": 0,
        "allow_bulk_edit": 0,
        "in_standard_filter": 0,
        "in_preview": 0,
        "read_only": 0,
        "length": 0,
        "translatable": 0,
        "hide_border": 0,
        "hide_days": 0,
        "hide_seconds": 0,
        "non_negative": 0,
        "is_virtual": 0,
        "sort_options": 0,
        "show_on_timeline": 0,
        "make_attachment_public": 0,
        "fields": [],
        "permissions": [],
        "actions": [],
        "links": [],
        "states": [],
      },
    ],
    "__dashboard": {
      "heatmap": true,
      "heatmap_message":
          "This is based on stock movement. See <a href=\"/app/query-report/Stock Ledger\">Stock Ledger</a> for details",
      "fieldname": "item_code",
      "non_standard_fieldnames": {
        "Work Order": "production_item",
        "Product Bundle": "new_item_code",
        "BOM": "item",
        "Batch": "item",
      },
      "transactions": [
        {
          "label": "Groups",
          "items": ["BOM", "Product Bundle", "Item Alternative"],
        },
        {
          "label": "Pricing",
          "items": ["Item Price", "Pricing Rule"],
        },
        {
          "label": "Sell",
          "items": [
            "Quotation",
            "Sales Order",
            "Delivery Note",
            "Sales Invoice",
          ],
        },
        {
          "label": "Buy",
          "items": [
            "Material Request",
            "Supplier Quotation",
            "Request for Quotation",
            "Purchase Order",
            "Purchase Receipt",
            "Purchase Invoice",
          ],
        },
        {
          "label": "Manufacture",
          "items": ["Production Plan", "Work Order", "Item Manufacturer"],
        },
        {
          "label": "Traceability",
          "items": ["Serial No", "Batch"],
        },
        {
          "label": "Stock Movement",
          "items": ["Stock Entry", "Stock Reconciliation"],
        },
      ],
      "internal_links": {},
    },
  };
}
